version: '3.9'

services:
  pda: 
    image: ghcr.io/pda-payroll/pda:latest
    restart: always
    environment:
      POSTGRES_USER: pdaAdmin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdaDB
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - 6969:6969
    networks:
      default:
        external:
          name: localhost
  db:
    image: postgres
    restart: always
    userns_mode: keep-id
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: pdaAdmin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdaDB
    ports:
      - 7734:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data:rw,U
    networks:
      default:
        external:
          name: localhost

  #  pgadmin:
  #    image: dpage/pgadmin4
  #    restart: always
  #    userns_mode: keep-id
  #    ports: 
  #      - 8008:80
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: admin@pda.net
  #      PGADMIN_DEFAULT_PASSWORD: admin@pda.net
  #    volumes:
  #      - ./pgadmin-data:/var/lib/pgadmin:rw,U
  #    networks:
  #      default:
  #        external:
  #          name: localhost

volumes:
  pgdata:
  #  pgadmin-data:
